server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://userservice/
          predicates:
            - Path=/users/**
        - id: DEPARTMENT-SERVICE
          uri: http://departmentservice/
          predicates:
            - Path=/departments/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
    hostname: localhost




